config/routes.rb
Rails.application.routes.draw do
  resources :articles
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  get '/@:username', to: 'accounts#show', as: :short_account

  resources :accounts, path: 'users', only: [:show], param: :username do
    resources :stream_entries, path: 'updates', only: [:show] do
      member do
        get :embed
      end
    end

    get :remote_follow,  to: 'remote_follow#new'
    post :remote_follow, to: 'remote_follow#create'

    resources :statuses, only: [:show] do
      member do
        get :activity
        get :embed
      end
    end

    resources :followers, only: [:index], controller: :follower_accounts
    resources :following, only: [:index], controller: :following_accounts
    resource :follow, only: [:create], controller: :account_follow
    resource :unfollow, only: [:create], controller: :account_unfollow

    resource :outbox, only: [:show], module: :activitypub
    resource :inbox, only: [:create], module: :activitypub
    resources :collections, only: [:show], module: :activitypub
  end

  resource :inbox, only: [:create], module: :activitypub  

  # Webfinger
  get '.well-known/host-meta', to: 'well_known/host_meta#show', as: :host_meta, defaults: { format: 'xml' }
  get '.well-known/webfinger', to: 'well_known/webfinger#show', as: :webfinger

  get 'home/index'

  get 'follows/search'
  resources :follows

  root to: 'home#index'
end

app/views/shared/_footer.html.erb
<footer class="blog-footer">
  <p>Federated blogging on <a href="https://www.w3.org/TR/activitypub/">ActivityPub</a></p>
  <p>
    <a href="#">Back to top</a>
  </p>
</footer>

app/views/shared/_header.html.erb
<div class="blog-header">
  <div class="container">
    <h1 class="blog-title">Hanatachi</h1>
    <p class="lead blog-description">Federated blogging</p>
  </div>
</div>

app/views/shared/_nav.html.erb
<div class="blog-masthead">
  <div class="container">
    <nav class="nav blog-nav">
      <%= link_to "Home", root_path, class: 'nav-link active' %>
      <% if can? :manage, Follow %>
        <%= link_to "Subscriptions", follows_path, class: 'nav-link' %>
      <% end %>
      <%= login_helper 'nav-link' %>
    </nav>
  </div>
</div>

app/views/shared/_sidebar.html.erb
<div class="col-sm-3 offset-sm-1 blog-sidebar">
  <div class="sidebar-module sidebar-module-inset">
    <h4>About</h4>
    <p>Etiam porta <em>sem malesuada magna</em> mollis euismod. Cras mattis consectetur purus sit amet fermentum. Aenean lacinia bibendum nulla sed consectetur.</p>
  </div>
  <div class="sidebar-module">
    <h4>Archives</h4>
    <ol class="list-unstyled">
      <li><a href="#">March 2014</a></li>
      <li><a href="#">February 2014</a></li>
      <li><a href="#">January 2014</a></li>
      <li><a href="#">December 2013</a></li>
      <li><a href="#">November 2013</a></li>
      <li><a href="#">October 2013</a></li>
      <li><a href="#">September 2013</a></li>
      <li><a href="#">August 2013</a></li>
      <li><a href="#">July 2013</a></li>
      <li><a href="#">June 2013</a></li>
      <li><a href="#">May 2013</a></li>
      <li><a href="#">April 2013</a></li>
    </ol>
  </div>
  <div class="sidebar-module">
    <h4>Elsewhere</h4>
    <ol class="list-unstyled">
      <li><a href="#">Mastodon</a></li>
      <li><a href="#">GNU social</a></li>
      <li><a href="#">Diaspora</a></li>
    </ol>
  </div>
</div>

app/views/shared/_subscriptions.html.erb
<div class="col-sm-6 offset-sm-1 blog-sidebar">
  <h2>Your subscriptions</h2>
  <% @account.following.each do |other_account| %>
    <p><%= other_account.acct %><p>
  <% end %>
</div>