config/routes.rb
Rails.application.routes.draw do
  resources :articles
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  get '/@:username', to: 'accounts#show', as: :short_account

  resources :accounts, path: 'users', only: [:show], param: :username do
    resources :stream_entries, path: 'updates', only: [:show] do
      member do
        get :embed
      end
    end

    get :remote_follow,  to: 'remote_follow#new'
    post :remote_follow, to: 'remote_follow#create'

    resources :statuses, only: [:show] do
      member do
        get :activity
        get :embed
      end
    end

    resources :followers, only: [:index], controller: :follower_accounts
    resources :following, only: [:index], controller: :following_accounts
    resource :follow, only: [:create], controller: :account_follow
    resource :unfollow, only: [:create], controller: :account_unfollow

    resource :outbox, only: [:show], module: :activitypub
    resource :inbox, only: [:create], module: :activitypub
    resources :collections, only: [:show], module: :activitypub
  end

  resource :inbox, only: [:create], module: :activitypub  

  # Webfinger
  get '.well-known/host-meta', to: 'well_known/host_meta#show', as: :host_meta, defaults: { format: 'xml' }
  get '.well-known/webfinger', to: 'well_known/webfinger#show', as: :webfinger

  get 'home/index'

  get 'follows/search'
  resources :follows

  root to: 'home#index'
end

app/models/follow.rb
class Follow < ApplicationRecord
  has_one :activity, as: :object

  belongs_to :account, required: true
  belongs_to :target_account, class_name: 'Account', required: true

  validates :account_id, uniqueness: { scope: :target_account_id }

  scope :recent, -> { reorder(id: :desc) }

  after_create do
    account.activities.create!(object: self, action: 'Follow')
  end
end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController
  RESULTS_LIMIT = 1

  load_resource except: :create
  authorize_resource

  def index
    @account = current_account
  end

  def search
    results =  SearchService.new.call(
      params[:q],
      RESULTS_LIMIT,
      resolving_search?,
      current_account
    )

    if results[:accounts].nil?
      redirect_to follows_path
    end

    @account = results[:accounts].first
    render 'confirm'
  end

  def create
    raise ActiveRecord::RecordNotFound if follow_params[:uri].blank?

    @account = FollowService.new.call(current_user.account, target_uri).try(:target_account)

    if @account.nil?
      username, domain = target_uri.split('@')
      @account         = Account.find_remote!(username, domain)
    end

    redirect_to follows_path
  end

  private

  def target_uri
    follow_params[:uri].strip.gsub(/\A@/, '')
  end

  def follow_params
    params.permit(:uri)
  end

  def resolving_search?
    params[:resolve] == 'true'
  end
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/views/follows/confirm.html.erb
<% content_for :main do %>
  <div class="col-sm-6 blog-main confirm-user-profile">
    <h2>Your are going to subscribe to</h2>
    <div class="light profile-sidebar-portlet bordered">
        <div class="profile-userpic text-center">
            <img src="<%= asset_path 'hanatachi_avatar.png' %>" class="img-responsive" alt=""> </div>
        <div class="profile-usertitle">
            <div class="profile-usertitle-name"><%= @account.display_name %></div>
            <div class="profile-usertitle-job">@<%= @account.acct %></div>
        </div>
        <div>
          <%= @account.note.html_safe unless @account.note.nil? %>
        </div>
        <div class="profile-userbuttons">
            <%= form_tag(follows_path, method: "post") do %>
              <%= hidden_field_tag :uri, @account.acct %>
              <%= submit_tag 'Confirm', class: 'btn btn-info  btn-block' %>
            <% end %>
        </div>
    </div>
  </div>
<% end %>

app/views/follows/index.html.erb
<% content_for :main do %>
  <div class="col-sm-5 blog-main">
    <h2>Subscribe to</h2>
    <%= form_tag(follows_search_path, method: "get") do %>
      <%= hidden_field_tag 'resolve', 'true' %>
      <div class="form-group">
        <%= text_field_tag(:q, @q, class: 'form-control') %>
      </div>
      <%= submit_tag("Search") %>
    <% end %>
  </div>
  <%= render 'shared/subscriptions' %>
<% end %>